//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /afs/asu.edu/users/j/j/o/jjose3/vendingmachine/vendingmachine/verif/clocker.vp
//  Source template: clocker
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

//clocker module





//clocker//
module clocker_unq1 (
		output logic  clk,
		output int clk_period 
		);

   real clk_period_ns ;
   int clk_half_period ;

   initial begin
     if ( $test$plusargs("clk_period") ) 
       begin
	  $value$plusargs("clk_period=%f", clk_period_ns);
	  clk_period = $rtoi(clk_period_ns*1000.0) ;
	  clk_half_period = clk_period / 2 ;
	  $display( "Using Clk Period= %f nS", clk_period_ns) ;
	  $display( "Using Clk Period= %d pS", clk_period) ;
       end else begin
           $display( "ERROR: No Clock Period Set, Try again") ;
	   $finish(2);
       end
     while(1) begin
	 #clk_half_period clk = 1'b0 ;
	 #clk_half_period clk = 1'b1 ;
      end
   end // initial begin

   
endmodule // clocker
