//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /afs/asu.edu/users/j/j/o/jjose3/vendingmachine/vendingmachine/verif/limiter.vp
//  Source template: limiter
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

//clocker module

//clocker//
module limiter_unq1 (
    input logic clk 
    );

    int maxCycles ;
    int cnt ;
   
   
    initial begin
        if ( $test$plusargs("maxCycles") ) begin
            $value$plusargs("maxCycles=%d", maxCycles );
            $display( "Maximum Cycles = %d ", maxCycles ) ;
        end else begin
            maxCycles = 0 ;
        end
        cnt = 0 ;
    end // initial begin

    always  @( posedge clk )  begin
        cnt <= cnt + 1 ;

        if( (cnt > maxCycles) && (maxCycles != 0) ) begin
            $display( "t:%t ERROR: Exceeded maximum number of cycles %d\n" , $time ,  maxCycles );
            $finish(2);
        end
    end

endmodule // clocker
